#!/bin/bash

# Input variables
programNumber=$1
mainProgram="animation${programNumber}"
libraryFlags="-lGL -lGLU -lglut -lGLEW -lassimp -lIL -ILU"

# Clean, build, and run main program
rm animation1
g++ -Wall -g -o $mainProgram "${mainProgram}.cpp" $libraryFlags
"./${mainProgram}"